In [122]:
import pandas as pd
import numpy as np
from torch import tensor
import torch

In [123]:
df = pd.read_csv(r"C:\Users\choco\Downloads\titanic\train.csv")

In [124]:
modes=df.mode().loc[0]

In [125]:
df.fillna(modes, inplace=True)


In [126]:
df.isna().sum()


PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [127]:
df['LogFare'] = np.log(df['Fare']+1)

In [128]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  24.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare    Cabin Embarked   LogFare  
0        0         A/5 21171   7.2500  B96 B98        S  2.110213  
1        0          PC 17599  71.2833      C85        C  4.280593  
2        0  STON/O2. 3101282   7.9250  B96 B98        S  2.188856  
3        0            113803  53.1000     C123        S  3.990834  
4        0            373450   8.0500  B96 B98        S  2.202765  
..     ...               ...      ...      ...      ...       ...  
886      0            211536  13.0000  B96 B98        S  2.639057  
887      0            112053  30.0000      B42        S  3.433987  
888      2        W./C. 6607  23.4500  B96 B98        S  3.196630  
889      0            111369  30.0000     C148        C  3.433987  
890      0            370376   7.7500  B96 B98        Q  2.169054  

[891 rows x 13 columns]

In [129]:
df['sex']=df['Sex'].map({"male":1,"female":0})
df['Embarked']=df['Embarked'].map({"S":1,"C":2,"Q":3})

In [130]:

t_dep = tensor(df.Survived)

In [131]:
indep_cols = ['Age', 'SibSp', 'Parch', 'LogFare','sex','Embarked','Pclass'] 
df[indep_cols] = df[indep_cols].astype(float)
t_indep = tensor(df[indep_cols].values, dtype=torch.float)
t_indep

tensor([[22.,  1.,  0.,  ...,  1.,  1.,  3.],
        [38.,  1.,  0.,  ...,  0.,  2.,  1.],
        [26.,  0.,  0.,  ...,  0.,  1.,  3.],
        ...,
        [24.,  1.,  2.,  ...,  0.,  1.,  3.],
        [26.,  0.,  0.,  ...,  1.,  2.,  1.],
        [32.,  0.,  0.,  ...,  1.,  3.,  3.]])

In [132]:
t_indep.shape


torch.Size([891, 7])

In [133]:
torch.manual_seed(23)

n_coeff = t_indep.shape[1]
coeffs = torch.rand(n_coeff)-0.5
coeffs

tensor([-0.0717, -0.2111, -0.0776, -0.1429,  0.4577, -0.3900, -0.2067])

In [134]:
#val,indices=t_indep.max(dim=0)
#t_indep = t_indep / val
t_indep = (t_indep - t_indep.mean(dim=0)) / t_indep.std(dim=0)



In [135]:
preds = (t_indep*coeffs).sum(axis=1)


In [136]:
preds

tensor([ 4.9508e-01, -9.8882e-01, -3.0434e-01, -3.1617e-01,  6.0224e-01,
        -5.7168e-01,  7.3299e-01, -2.0570e-02, -5.4755e-01, -9.8101e-01,
        -5.7347e-01, -1.5017e-01,  6.8377e-01, -2.7972e-01, -2.3794e-01,
        -3.0983e-01, -1.4851e+00,  8.4485e-01, -6.3444e-01, -8.9502e-01,
         6.8818e-01,  7.9050e-01, -1.4735e+00,  9.2894e-01, -1.0107e+00,
        -1.2324e+00,  6.2530e-02, -8.0894e-02, -1.5199e+00,  6.6456e-01,
         2.8548e-01, -1.0180e+00, -1.5177e+00,  6.4559e-01,  2.3870e-03,
         6.0636e-01,  6.2455e-02,  6.7833e-01, -7.5525e-01, -1.0908e+00,
        -5.9552e-01, -3.8714e-01,  5.0965e-02, -1.1602e+00, -1.4927e+00,
         6.6203e-01, -8.4523e-01, -1.5177e+00, -4.7002e-01, -5.6222e-01,
        -3.2941e-01,  6.8246e-01, -1.0593e+00, -4.2822e-01, -6.2464e-02,
         9.5068e-01, -6.7374e-02,  3.7997e-02, -4.9952e-01, -6.6293e-01,
         7.3325e-02, -2.0055e-01,  5.2129e-01, -1.6742e-01,  3.7244e-01,
        -3.2558e-01, -1.1086e-01,  6.8745e-01, -1.2

In [137]:
loss = torch.abs(preds-t_dep).mean()
loss

tensor(0.8992)

In [138]:
def cal_pred(coeffs, indeps): return torch.sigmoid((indeps@coeffs).sum(axis=1))
def cal_loss(q,t_indep,t_dep): return torch.abs(cal_pred(q,t_indep)-t_dep).mean()

In [149]:
from sklearn.model_selection import train_test_split

# Split data into training and validation sets
trn_indep, val_indep, trn_dep, val_dep = train_test_split(t_indep, t_dep, test_size=0.2, random_state=42)

# Check the length of training and validation sets
len(trn_indep), len(val_indep)



(712, 179)

In [150]:
def init_coeffs(): return (torch.rand(n_coeff, 1)*0.1).requires_grad_()

def update_coeffs(coeffs, lr):
    coeffs.sub_(coeffs.grad * lr)
    coeffs.grad.zero_()
def one_epoch(coeffs, lr):
    loss = cal_loss(coeffs, trn_indep, trn_dep)
    loss.backward()
    with torch.no_grad(): update_coeffs(coeffs, lr)
    print(f"{loss:.3f}", end="; ")


In [151]:
def train_model(epochs=30, lr=0.01):
    torch.manual_seed(442)
    coeffs = init_coeffs()
    for i in range(epochs): one_epoch(coeffs, lr=lr)
    return coeffs

In [152]:
def acc(coeffs): return (val_dep.bool()==(cal_pred(coeffs, val_indep)>0.5)).float().mean()


In [153]:
coeffs = train_model(lr=100)

0.712; 13.085; 12.666; 11.233; 9.634; 7.868; 6.047; 3.053; 2.607; 21.923; 20.944; 17.878; 17.526; 17.405; 17.161; 17.392; 16.585; 16.612; 16.222; 15.961; 15.021; 14.501; 13.374; 12.103; 10.254; 9.619; 7.906; 6.424; 4.195; 2.630; 

In [154]:
acc(coeffs)


tensor(0.7542)

Basic Neural Network


In [165]:
def init_coeffs(n_hidden=20):
    layer1 = (torch.rand(n_coeff, n_hidden)-0.5)/n_hidden
    layer2 = torch.rand(n_hidden, 1)-0.3
    const = torch.rand(1)[0]
    return layer1.requires_grad_(),layer2.requires_grad_(),const.requires_grad_()

In [166]:
import torch.nn.functional as F

def cal_pred(coeffs, indeps):
    l1,l2,const = coeffs
    res = F.relu(indeps@l1)
    res = res@l2 + const
    return torch.sigmoid(res)

In [167]:
def update_coeffs(coeffs, lr):
    for layer in coeffs:
        layer.sub_(layer.grad * lr)
        layer.grad.zero_()

In [168]:
coeffs = train_model(lr=0.5)

0.778; 0.737; 0.706; 0.680; 0.657; 0.637; 0.619; 0.602; 0.587; 0.572; 0.559; 0.546; 0.535; 0.524; 0.515; 0.506; 0.498; 0.491; 0.484; 0.479; 0.474; 0.469; 0.466; 0.462; 0.459; 0.457; 0.454; 0.452; 0.451; 0.449; 

In [169]:
acc(coeffs)

tensor(0.7821)

0.712; 0.653; 0.613; 0.585; 0.565; 0.550; 0.538; 0.528; 0.521; 0.514; 0.509; 0.505; 0.501; 0.498; 0.496; 0.494; 0.492; 0.490; 0.488; 0.487; 0.486; 0.485; 0.484; 0.483; 0.483; 0.482; 0.482; 0.481; 0.481; 0.480; 0.480; 0.480; 0.479; 0.479; 0.479; 0.479; 0.478; 0.478; 0.478; 0.478; 0.478; 0.478; 0.478; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.477; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476; 0.476;

Deep learning

In [170]:
def init_coeffs():
    hiddens = [10, 10]  # <-- set this to the size of each hidden layer you want
    sizes = [n_coeff] + hiddens + [1]
    n = len(sizes)
    layers = [(torch.rand(sizes[i], sizes[i+1])-0.3)/sizes[i+1]*4 for i in range(n-1)]
    consts = [(torch.rand(1)[0]-0.5)*0.1 for i in range(n-1)]
    for l in layers+consts: l.requires_grad_()
    return layers,consts

In [171]:
import torch.nn.functional as F

def cal_pred(coeffs, indeps):
    layers,consts = coeffs
    n = len(layers)
    res = indeps
    for i,l in enumerate(layers):
        res = res@l + consts[i]
        if i!=n-1: res = F.relu(res)
    return torch.sigmoid(res)

In [172]:
def update_coeffs(coeffs, lr):
    layers,consts = coeffs
    for layer in layers+consts:
        layer.sub_(layer.grad * lr)
        layer.grad.zero_()

In [175]:
coeffs = train_model(lr=0.5)


0.688; 0.660; 0.646; 0.626; 0.595; 0.544; 0.508; 0.485; 0.471; 0.461; 0.454; 0.449; 0.445; 0.442; 0.440; 0.438; 0.436; 0.435; 0.434; 0.433; 0.432; 0.431; 0.431; 0.430; 0.429; 0.429; 0.428; 0.428; 0.427; 0.427; 

In [176]:
acc(coeffs)

tensor(0.7709)